### ISSUE TITLE
Cannot find module './services/npm'

### ISSUE THREAD

**Issue by zkochan** [atlassian/lerna-semantic-release#4]
Is it ready to be used? I've configured `lerna-semantic-release` on the [mos](https://github.com/mosjs/mos) monorepo but both on Travis and locally I am getting this error on the `pre` step:

```
> @ prerelease C:\src\mos
> lerna-semantic-release pre

module.js:338
    throw err;
          ^
Error: Cannot find module './services/npm'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\src\mos\node_modules\lerna-semantic-release\bin\lerna-semantic-release.js:5:11)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
```

[Here's the error in the travis job](https://travis-ci.org/mosjs/mos/jobs/136982621#L4286)

**Comment by jpnelson** [comment]
Sorry @zkochan ! It was in a temporary state at that point, I'm not sure how it got published.

It should work in v1.1.4
